language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt --quiet
  - pip install -r requirements-dev.txt --quiet
script:
  - black --check .
  - flake8
  - isort **/*.py -c -vb
  - pytest
cache: pip
